(function(){'use strict';var f;function g(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var h=g(this),l="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var q={a:!0},r={};try{r.__proto__=q;p=r.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=n;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var u=this||self;function v(a){return a};function w(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a}function x(a,b,c){return a.hasAttribute(b)?a.getAttribute(b):c};function y(a,b){this.j=a;this.g=b}y.prototype.i=function(a){a=a.coords;this.j(a.latitude,a.longitude,a.accuracy)};y.prototype.h=function(a){this.g(a.message)};function z(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d}function aa(a,b){function c(d){a.removeEventListener("load",c);b(d)}a.addEventListener("load",c)};var A;function B(a){this.g=a}B.prototype.toString=function(){return this.g+""};B.prototype.i=!0;B.prototype.h=function(){return this.g.toString()};var ba={};function C(a){this.g=a}C.prototype.toString=function(){return this.g.toString()};C.prototype.i=!0;C.prototype.h=function(){return this.g.toString()};function D(a){return a instanceof C&&a.constructor===C?a.g:"type_error:SafeUrl"}var E;try{new URL("s://g"),E=!0}catch(a){E=!1}var ca=E,da={};function F(a){if(!(a instanceof C||a instanceof C)){a="object"==typeof a&&a.i?a.h():String(a);b:{var b=a;if(ca){try{var c=new URL(b)}catch(d){b="https:";break b}b=c.protocol}else c:{c=document.createElement("a");try{c.href=b}catch(d){b=void 0;break c}b=c.protocol;b=":"===b||""===b?"https:":b}}"javascript:"===b&&(a="about:invalid#zClosurez");a=new C(a,da)}u.open(D(a),"")};/*

 SPDX-License-Identifier: Apache-2.0
*/
var ea="function"===typeof URL;function G(a){if(a instanceof C)a=D(a);else{b:if(ea){try{var b=new URL(a)}catch(c){b="https:";break b}b=b.protocol}else c:{b=document.createElement("a");try{b.href=a}catch(c){b=void 0;break c}b=b.protocol;b=":"===b||""===b?"https:":b}a="javascript:"!==b?a:void 0}return a};function H(){for(var a=["google","load"],b=window,c=0;b&&c<a.length;c++)b=b[a[c]];this.g=b?0:2;this.h=[]}H.prototype.i=function(){for(var a=this.g=0;a<this.h.length;a++)this.h[a]();this.h=[]};
H.prototype.load=function(a){a&&(0==this.g?a():this.h.push(a));if(2==this.g){this.g=1;var b=document;a="SCRIPT";"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());a=b.createElement(a);aa(a,this.i.bind(this));a.setAttribute("type","text/javascript");a.setAttribute("async",!0);b="https://www.google.com/jsapi";if(void 0===A){var c=null;var d=u.trustedTypes;if(d&&d.createPolicy){try{c=d.createPolicy("goog#html",{createHTML:v,createScript:v,createScriptURL:v})}catch(k){u.console&&u.console.error(k.message)}A=
c}else A=c}b=(c=A)?c.createScriptURL(b):b;b=new B(b,ba);a.src=b instanceof B&&b.constructor===B?b.g:"type_error:TrustedResourceUrl";var e,m;(e=(b=null==(m=(e=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:m.call(e,"script[nonce]"))?b.nonce||b.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",e);(e=document.getElementsByTagName("script")[0])?e.parentNode.insertBefore(a,e):document.getElementsByTagName("head")[0].appendChild(a)}};var I=null;function fa(a){I||(I=new H);I.load(function(){google.load("maps","3.28",a)})};function ha(a,b){this.h=a;this.g=new google.maps.places.PlacesService(b)}function ia(a,b,c){b={location:b.getCenter()||void 0,radius:3*b.getRadius(),query:a.h};a.g.textSearch(b,function(d,e){c(e==google.maps.places.PlacesServiceStatus.OK?d:[])})};function J(a){a=a.trim();return window.Enabler?window.Enabler.getUrl(a):a};function K(a,b,c,d,e,m,k){this.N=a;this.g=null;this.U=c;this.S=d;this.T=e;this.V=m;this.h=k;this.F=k.radius;this.H=null;this.l=0;this.i=this.m=this.I=this.v=this.A=this.u=this.J=this.G=this.B=null;this.j=[];this.s=[];this.K=null;this.o=b.ownerDocument.createElement("div");this.o.className="map";b.appendChild(this.o)}
function L(a,b,c){function d(){e.removeEventListener("load",d,!1);e.removeEventListener("error",d,!1);e.removeEventListener("abort",d,!1);c()}var e=a.o.ownerDocument.createElement("img");e.addEventListener("load",d,!1);e.addEventListener("error",d,!1);e.addEventListener("abort",d,!1);e.setAttribute("src",J(b))}f=K.prototype;
f.W=function(){this.l--;if(0==this.l){var a=this.h;if(a.lat&&a.lng){var b=new google.maps.LatLng(a.lat,a.lng);var c=a.zoom;var d=!0}else b=new google.maps.LatLng(0,0),c=1;c=new google.maps.Map(this.o,{center:b,zoom:c,mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControl:!1});this.K=c.getBounds();google.maps.event.addListener(c,"dragend",this.aa.bind(this));google.maps.event.addListener(c,"click",this.ga.bind(this));var e=J(this.h.markerSource);this.B={url:e,size:new google.maps.Size(34,34),origin:new google.maps.Point(0,
0)};this.G={url:e,size:new google.maps.Size(34,34),origin:new google.maps.Point(34,0)};this.J={url:e,size:new google.maps.Size(37,34),origin:new google.maps.Point(68,0),anchor:new google.maps.Point(10,34)};this.A={url:J(this.h.gpsIconSource),size:new google.maps.Size(32,32),anchor:new google.maps.Point(0,0)};this.H=new ha(a.query||"*",c);d&&new google.maps.Marker({position:b,map:c,icon:this.A});this.g=c;this.U()}};
f.aa=function(){if(this.m){for(var a=this.g.getBounds(),b=!0,c=0;c<this.s.length;c++)if(a.contains(this.s[c].geometry.location||null)){b=!1;break}b&&!this.m.getBounds().contains(this.g.getCenter())&&(this.C(),this.V())}};f.C=function(){this.i&&(this.i.setIcon(this.B),this.i=null)};
function M(a,b,c,d){a.g&&(b=new google.maps.LatLng(b,c),c=a.g,a.v=b,c.setCenter(b),new google.maps.Marker({position:b,map:c,icon:a.A}),d&&(a.F=d,a.I=new google.maps.Circle({center:b,radius:a.F,map:c,fillColor:"#a2d1f5",fillOpacity:.5,strokeWeight:0}),c.fitBounds(a.I.getBounds())))}
f.P=function(a,b){for(var c=0;c<this.j.length;c++)this.j[c].setMap(null),google.maps.event.clearInstanceListeners(this.j[c]);this.j.length=0;this.s=b;for(c=0;c<b.length;c++){var d=new google.maps.Marker({position:b[c].geometry.location,map:this.g,icon:this.B,ia:this.J});google.maps.event.addListener(d,"click",this.O.bind(this,c));this.j.push(d)}this.g.fitBounds(this.m.getBounds());if(c=0<b.length)d=this.g.getBounds(),b=b[0].geometry.location||null,d&&!d.contains(b)&&(d.extend(b),this.g.fitBounds(d));
a(c)};f.ga=function(){this.C();this.S()};f.O=function(a){this.C();this.i=this.j[a];this.T(this.s[a],this.X.bind(this))};f.X=function(a){this.i.setIcon(this.G);this.g.panTo(this.i.getPosition());this.g.panBy(0,a)};f.Y=function(a,b,c,d){d==google.maps.GeocoderStatus.OK?(b=c[0].geometry.location,this.g.setCenter(b),this.g.fitBounds(c[0].geometry.viewport),M(this,b.lat(),b.lng()),a()):b()};function N(a,b,c,d){this.o=a;this.l=null;this.s=c;this.u=d;this.g=b.ownerDocument.createElement("div");this.g.className="ip";a=b.ownerDocument.createElement("div");a.className="bg";this.g.appendChild(a);c=b.ownerDocument.createElement("a");c.className="dir";c.appendChild(b.ownerDocument.createElement("div"));a.appendChild(c);c.addEventListener("click",this.B.bind(this),!1);c=b.ownerDocument.createElement("div");c.className="res";this.m=b.ownerDocument.createElement("div");this.m.className="title";
this.j=b.ownerDocument.createElement("div");this.j.className="address";this.i=b.ownerDocument.createElement("div");this.i.className="tel";d=this.h=b.ownerDocument.createElement("a");var e=G("#");void 0!==e&&(d.href=e);this.i.appendChild(this.h);c.appendChild(this.m);c.appendChild(this.j);c.appendChild(this.i);a.appendChild(c);this.h.addEventListener("click",this.v.bind(this));c=b.ownerDocument.createElement("a");c.className="close";c.appendChild(b.ownerDocument.createElement("div"));a.appendChild(c);
c.addEventListener("click",this.A.bind(this),!1);O(this);b.appendChild(this.g)}function O(a){a.g.classList.add("hidden")}N.prototype.v=function(a){a.preventDefault();a=this.h.href;z("calllocation",this.o,{url:a}).detail.handled||F(a)};N.prototype.A=function(a){a.preventDefault();O(this);this.s()};N.prototype.B=function(a){a.preventDefault();this.l&&this.u(this.l)};function ja(a){var b=document.createElement("div");b.className="bg hidden";var c=document.createElement("div");c.className="loading";c.appendChild(document.createElement("div"));b.appendChild(c);this.g=b;a.appendChild(this.g)}function P(a){a.g.classList.remove("hidden")}function Q(a){a.g.classList.add("hidden")};function R(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")}function S(a){if(R(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&R(a))return a;return null};function T(a,b,c,d){this.h=b;this.m=c;this.g=ka(this,d);this.l=this.g.querySelector("form");this.o=this.g.querySelector("input");this.s=this.g.querySelector(".title");this.j=this.g.querySelector(".btns");a.appendChild(this.g)}
function ka(a,b){var c=document.createElement("div"),d=document.createElement("div");d.classList.add("diag");c.appendChild(d);var e=document.createElement("div");e.classList.add("title");e.textContent=b.title;d.appendChild(e);e=document.createElement("div");e.classList.add("btns");d.appendChild(e);var m=document.createElement("form");m.setAttribute("method","get");d.appendChild(m);var k=document.createElement("input");k.placeholder=b.geocodePlaceholder;k.type="search";m.appendChild(k);a.h?(U(e,b.gpsLabel,
a.h),U(e,b.geocodeLabel,a.i.bind(a,b.geocodeTitle))):e.classList.add("hidden");b=c.querySelector("form");b.addEventListener("submit",function(la){la.preventDefault();this.m(k.value)}.bind(a),!1);a.h&&b.classList.add("hidden");c.classList.add("bg");return c}function U(a,b,c){var d=document.createElement("a");d.textContent=b;d.addEventListener("click",function(e){e.preventDefault();c()},!1);d.setAttribute("href","#");a.appendChild(d)}function V(a){a.g.classList.add("hidden")}
T.prototype.i=function(a){this.s.textContent=a;this.j.classList.add("hidden");this.l.classList.remove("hidden");this.g.classList.remove("hidden");this.o.focus()};var ma=["start-latitude","start-longitude","query"];function W(){var a=HTMLElement.call(this)||this;a.u=!1;a.m=!1;a.s=!1;return a}var X=HTMLElement;W.prototype=l(X.prototype);W.prototype.constructor=W;if(t)t(W,X);else for(var Y in X)if("prototype"!=Y)if(Object.defineProperties){var Z=Object.getOwnPropertyDescriptor(X,Y);Z&&Object.defineProperty(W,Y,Z)}else W[Y]=X[Y];f=W.prototype;
f.connectedCallback=function(){if(!this.g){for(;this.firstChild;)this.removeChild(this.firstChild);var a={geocodeFailure:x(this,"msg-geocode-failure","Your location could not be determined. Please enter a valid address."),gpsIconSource:x(this,"gps-src","assets/location.png"),limit:w(this,"result-limit",20),locationDialogConfig:{title:x(this,"msg-start-position-prompt","How would you like us to get your position?"),gpsLabel:x(this,"msg-gps-button-label","Use GPS"),geocodeLabel:x(this,"msg-manual-position-button-label",
"Enter address or zip code"),geocodeTitle:x(this,"msg-manual-position-prompt","Enter address or zip code"),geocodePlaceholder:x(this,"msg-manual-position-placeholder","Address or zip code")},markerSource:x(this,"marker-src","assets/marker_sprite.png"),noResultsError:x(this,"msg-no-results-found","No results found near you."),radius:w(this,"search-radius",4E4),requestLocation:this.hasAttribute("request-user-location")||!this.hasAttribute("start-latitude")||!this.hasAttribute("start-longitude"),zoom:w(this,
"start-zoom",16),showLocationBar:this.hasAttribute("show-location-bar"),includeDirections:this.hasAttribute("include-directions"),includeClickToCall:this.hasAttribute("include-click-to-call"),includeDrapeImage:this.hasAttribute("include-drape-image")};this.hasAttribute("query")&&(a.query=this.getAttribute("query"));this.hasAttribute("start-latitude")&&(a.lat=parseFloat(this.getAttribute("start-latitude")));this.hasAttribute("start-longitude")&&(a.lng=parseFloat(this.getAttribute("start-longitude")));
this.hasAttribute("client-id")&&(a.clientId=this.getAttribute("client-id"));this.hasAttribute("api-key")&&(a.apiKey=this.getAttribute("api-key"));a.showLocationBar&&this.hasAttribute("location-bar-color")&&(a.locationBarColor=this.getAttribute("location-bar-color"));a.includeDrapeImage&&this.hasAttribute("drape-image-source")&&(a.drapeImageSource=this.getAttribute("drape-image-source"));this.l=a;var b=this.ownerDocument.createElement("div");b.className="sizer";this.g=new K(this,b,this.ha.bind(this),
this.M.bind(this),this.R.bind(this),this.D.bind(this),a);this.o=navigator.geolocation?new y(this.fa.bind(this),this.da.bind(this)):null;this.j=new T(b,this.o&&this.ea.bind(this),this.ca.bind(this),a.locationDialogConfig);a.requestLocation||V(this.j);this.h=new ja(b);this.appendChild(b);this.v=b}this.gwdIsLoaded()||((a=S(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());this.gwdIsActive()||((a=S(this))?a.gwdIsActive()&&this.gwdActivate():this.gwdActivate());a=this.g;a.g&&google.maps.event.trigger(a.g,
"resize")};f.attributeChangedCallback=function(a,b,c){if(this.g)switch(a){case "query":this.g.h.query=c||"";break;case "start-latitude":this.g.h.lat=parseFloat(c);break;case "start-longitude":this.g.h.lng=parseFloat(c)}};
f.gwdLoad=function(){if(!this.s){this.s=!0;var a=this.g,b=a.W.bind(a);a.l=2;L(a,a.h.markerSource,b);a.l++;L(a,a.h.gpsIconSource,b);a.l++;var c=a.h.clientId;a=a.h.apiKey;var d="";a&&!c&&(d="&key="+a);fa({callback:b,other_params:"sensor=true&libraries=places"+(c?"&client="+c:"")+d});b()}};f.gwdIsLoaded=function(){return this.u};f.gwdActivate=function(){this.classList.remove("deactivated");this.m=!0};f.gwdDeactivate=function(){this.classList.add("deactivated");this.m=!1};f.gwdIsActive=function(){return this.m};
f.setCenter=function(a,b,c){Q(this.h);M(this.g,a,b,c);this.D()};f.ha=function(){this.l.requestLocation||this.D();this.classList.add("ready");this.u=!0;z("ready",this)};f.ea=function(){P(this.h);V(this.j);var a=this.o;navigator.geolocation.getCurrentPosition(a.i.bind(a),a.h.bind(a))};f.fa=function(a,b,c){this.setCenter(a,b,c)};f.da=function(a){Q(this.h);this.j.i(a)};
f.ca=function(a){P(this.h);V(this.j);var b=this.g,c=this.D.bind(this),d=this.ba.bind(this);b.g&&(b.u||(b.u=new google.maps.Geocoder),b.u.geocode({address:a,bounds:b.K},b.Y.bind(b,c,d)))};f.D=function(){if(this.l.query){P(this.h);var a=this.g,b=this.L.bind(this);if(a.g){var c=a.F,d=10-a.g.getZoom();0<d&&(c*=d);a.m=new google.maps.Circle({center:a.g.getCenter(),radius:c});ia(a.H,a.m,a.P.bind(a,b))}}else Q(this.h);this.M();z("mapopen",this)};
f.L=function(a){Q(this.h);a?z("resultsfound",this):(this.j.i(this.l.geocodeFailure),z("resultsnotfound",this))};f.ba=function(){this.L(!1)};f.M=function(){this.i&&O(this.i)};
f.R=function(a,b){this.i||(this.i=new N(this,this.v,this.g.C.bind(this.g),this.Z.bind(this)));var c=this.i;c.l=a;c.m.textContent=a.name;var d=a.vicinity||a.formatted_address;d=d.replace(/, /,",\n");c.j.textContent=d;if(a.formatted_phone_number){c.i.classList.remove("hidden");c.h.textContent=a.formatted_phone_number;d=c.h;var e=G("tel:"+a.formatted_phone_number.replace(/[^\d]/g,""));void 0!==e&&(d.href=e)}else c.i.classList.add("hidden");c.g.classList.remove("hidden");b(this.i.g.firstChild.offsetHeight/
2);b=a.geometry.location.lat();a=a.geometry.location.lng();z("pinclick",this,{lat:b,lng:a})};f.Z=function(a){var b=this.g;if(b.g){var c=b.v?b.v.toString():"";a=encodeURIComponent(a.formatted_address);c="https://maps.google.com/maps?saddr="+escape(c)+"&daddr="+a;z("getdirections",b.N,{url:c}).detail.handled||F(c)}};h.Object.defineProperties(W,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ma}}});customElements.define("gwd-map",W);}).call(this);
